version: '3.8'

services:
  web:
    build: .
    command: 
      # python /goallens/manage.py runserver 0.0.0.0:8000
      ["./wait-for-it.sh", "-t", "60", "db:5432", "--", "python", "/goallens/manage.py", "runserver", "0.0.0.0:8000"]

    volumes:
      - .:/goallens
    ports:
      - 8000:8000
    depends_on:
      - "db"
  db:
    image: postgres:14.3
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      # - "POSTGRES_DB=postgres"
      # - "POSTGRES_USER=postgres"
      # - "POSTGRES_PASSWORD=postgres"
    ports:
      - 5432:5432

volumes:
  postgres_db: