version: '3.9'

services:
  web:
    build:
      context: .
    restart: always
    volumes:
      - static_prod:/vol/web/static_prod
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    depends_on:
      - db
  
  db:
    image: postgres:14.3
    restart: always
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"

  proxy:
    build:
      context: ./nginx_proxy
    restart: always
    depends_on:
      - web
    ports:
      - "80:8000"
    volumes:
      - static_prod:/vol/static_prod

volumes:
  postgres_db:
  static_prod: