version: '3.8'

services:
  web:
    build: .
    command: 
      ["./wait-for-it.sh", "-t", "60", "db:5432", "--", "python", "/goallens/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/goallens
    ports:
      - 8000:8000
      - 35729:35729 # for django livereload
    depends_on:
      - "db"
      - "selenium"

  db:
    image: postgres:14.3
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432

  selenium:
    image: selenium/standalone-firefox:99.0
    ports:
      - 4444:4444
    restart: always

volumes:
  postgres_db: