version: '3.8'

services:
  web:
    build: .
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "/goallens/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/goallens
    ports:
      - 8000:8000
    depends_on:
      - "db"
  db:
    image: mysql:8-oracle
    environment:
      - "MYSQL_DATABASE=goallens"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    ports:
      - 3306:3306