# Generated by Django 4.0.4 on 2022-05-24 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sourcing', '0002_alter_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.CharField(default=None, max_length=16, primary_key=True, serialize=False)),
                ('competition', models.CharField(max_length=45)),
                ('season', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SC', 'SCHEDULED'), ('LI', 'LIVE'), ('FI', 'FINISHED')], max_length=2)),
                ('goals_home', models.SmallIntegerField(blank=True, null=True)),
                ('goals_away', models.SmallIntegerField(blank=True, null=True)),
                ('xG_home', models.DecimalField(decimal_places=2, max_digits=4)),
                ('xG_away', models.DecimalField(decimal_places=2, max_digits=4)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_id', to='data_sourcing.team')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_id', to='data_sourcing.team')),
            ],
            options={
                'db_table': 'fixtures',
            },
        ),
    ]
