# Generated by Django 4.0.4 on 2022-05-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sourcing', '0003_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='xG_away',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='xG_home',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
