# Generated by Django 4.0.4 on 2022-05-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sourcing', '0004_alter_fixture_xg_away_alter_fixture_xg_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='status',
        ),
    ]
