# Generated by Django 4.0.5 on 2022-08-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sourcing', '0005_remove_fixture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='id',
            field=models.CharField(default=None, max_length=32, primary_key=True, serialize=False),
        ),
    ]
